name: 💡 Suggestion
description: Suggesst us how to improvie
labels: ["suggestion", "triage"]
title: "[<application>] <title>"
body:
  - type: markdown
    id: introduction
    attributes:
      value: |
        Thank you for reporting a suggestion, we really appreciate your feedback!
        
        Please ensure the ticket title contains the proper application name (ex: [wordpress] Your title here).
  - type: textarea
    id: description
    attributes:
      label: Describe your issue as much as you can
      description: Please add any extra deailed information you can provide us.
    validations:
      required: true