name: 🔧 Technical issue
description: Create a report to help you
labels: ["tech issues", "triage"]
body:
  - type: markdown
    id: introduction
    attributes:
      value: |
        Thank you for reporting an issue. Before you open the technical issue report please:
          - Look for your issue in the [resolved ones](https://github.com/bitnami/vms/issues?q=is%3Aissue+is%3Aclosed), maybe we solved similar issues before.
          - If you didn't find in the resolved ones, we suggest you to look on the [on going ones](https://github.com/bitnami/vms/issues).
        If that information didn't help you, please fill in as much of the following form as you are able.
  - type: input
    id: title
    attributes:
      label: Name of the application
      description: Name of the affected application
      placeholder: wordpress
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you using?
      options:
        - Google Cloud Platform
        - AWS
        - Azure
        - VMware Marketplace
        - Bitnami Cloud Hosting
        - Virtual Machine
        - OSX VM
        - Installers
    validations:
      required: true
  - type: input
    id: bndiagnosticID
    attributes:
      label: bndiagnostic ID
      placeholder: ex. 849fabe0-d11f-11cb-4a34-e4ec5361be461
    validations:
      required: true
  - type: textarea
    id: bndiagnosticOutput
    attributes:
      label: bndiagnostic output
      description: Enter output a summarized output of the tool (please, ensure there is no sensitive data)
      placeholder: |
        ? Apache: Found possible issues
        ? Connectivity: Found possible issues
        ? Resources: Found possible issues
          https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/
          https://docs.bitnami.com/general/faq/administration/use-firewall/
    validations:
      required: false
  - type: input
    id: bndiagnosticReason
    attributes:
      label: bndiagnostic failure reason
      placeholder: ex. The suggested guides are not related with my issue
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe your issue as much as you can
      description: Please add any extra deailed information you can provide us.
    validations:
      required: true