# This workflow is built to manage the triage support by using GH issues.

name: Cards movements
on:
  project_card:
    types:
      - moved
env:
  IN_PROGRESS_COLUMN_ID: 18834407
  TRIAGE_COLUMN_ID: 18834406
  SOLVED_COLUMN_ID: 18834409
  ON_HOLD_COLUMN_ID: 18834408
permissions:
  repository-projects: read
  issues: write
jobs:
  label-card:
    runs-on: ubuntu-latest
    steps:
      - name: On hold labeling
        # Only if moved into on hold
        if: ${{ github.event.project_card.column_id == env.ON_HOLD_COLUMN_ID  }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "on-hold"
          remove-labels: "triage"
      - name: In progress labeling
        # Only if moved into In progress
        if: ${{ github.event.project_card.column_id == env.IN_PROGRESS_COLUMN_ID  }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "in-progress"
          remove-labels: "on-hold, triage"
      - name: Solved labeling
        # Only if moved into Solved
        if: ${{ github.event.project_card.column_id == env.SOLVED_COLUMN_ID  }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "solved"
          remove-labels: "in-progress, on-hold, triage"
  assign-assignee-if-needed:
    runs-on: ubuntu-latest
    steps:
      - name: Assign to a person to work on it
        # Only if moved into In progress FROM Triage
        if: ${{ github.event.project_card.column_id == env.IN_PROGRESS_COLUMN_ID  }} && ${{ github.event.project_card.changes != null }} && $ {{ github.event.project_card.changes.column_id }} && $ {{ github.event.project_card.changes.column_id == env.TRIAGE_COLUMN_ID }}
        uses: pozil/auto-assign-issue@v1.6.3
        with:
          numOfAssignee: 1
          assignees: 'gongomgra,jotamartos,mdhont,joancafom,dgomezleon'
          removePreviousAssignees: true
          # teams: XXX
          repo-token: "${{ secrets.GITHUB_TOKEN }}"