name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          stale-issue-message: 'This Issue has been automatically marked as "stale" because it has not had recent activity (for 15 days). It will be closed if no further activity occurs. Thanks for the feedback.'
          stale-pr-message: 'This Pull Request has been automatically marked as "stale" because it has not had recent activity (for 15 days). It will be closed if no further activity occurs. Thank you for your contribution.'
          close-issue-message: 'Due to the lack of activity in the last 5 days since it was marked as "stale", we proceed to close this Issue. Do not hesitate to reopen it later if necessary.'
          close-pr-message: 'Due to the lack of activity in the last 5 days since it was marked as "stale", we proceed to close this Pull Request. Do not hesitate to reopen it later if necessary.'
          days-before-stale: 15
          days-before-close: 5
          exempt-issue-labels: 'on-hold'
          exempt-pr-labels: 'on-hold'
          operations-per-run: 500
    autoarchive-cards-job:
      runs-on: ubuntu-latest
      name: Autoarchive Done Column Cards
      steps:
        # - name: Checkout
        #  uses: actions/checkout@v2
        - name: The autoarchive action
          uses: kin/gh-action-autoarchive-stale-cards-for-column@v1.0
          id: archive
          with:
            # Required: personal access token with permissions to archive cards
            access-token: "${{ secrets.GITHUB_TOKEN }}"
            # Required: String with repo name (e.g. 'kin/gh-action-autoarchive-issues-for-column' should be 'gh-action-autoarchive-issues-for-column' here)
            repository: 'my-repo-name'
            # Required: String with owner name only (e.g. 'kin/gh-action-autoarchive-issues-for-column' should be 'kin' here)
            repository-owner: 'the-owner'

            # Required: String with name of project the column is in (case insensitive)
            project-name: 'My Project'

            # Required: String with column name for (case insensitive)
            column-to-archive: 'Done'

            # Required: Integer for how many days must have elapsed since the last time this card was touched
            days-old: 5